#!/bin/bash

# qenv.sh - Script to create .env file from config.py variables

# Output file
ENV_FILE=".env"

# Function to write variable to .env if not empty
write_env() {
    local var_name=$1
    local var_value=$2
    if [ ! -z "$var_value" ]; then
        echo "$var_name=$var_value" >> "$ENV_FILE"
    fi
}

# Start with a clean .env file
echo "# .env file generated by qenv.sh" > "$ENV_FILE"

# Default values from config.py
write_env "API_ID" "18136872"
write_env "API_HASH" "312d861b78efcd1b02183b2ab52a83a4"
write_env "BOT_TOKEN" ""
write_env "OWNER_USERNAME" "x_ifeelram"
write_env "BOT_USERNAME" "BillaProbot"
write_env "BOT_NAME" ""
write_env "MONGO_DB_URI" ""
write_env "DURATION_LIMIT" "17000"
write_env "LOGGER_ID" ""
write_env "OWNER_ID" "5960968099"
write_env "HEROKU_APP_NAME" ""
write_env "HEROKU_API_KEY" ""
write_env "UPSTREAM_REPO" "https://github.com/VT7org/nothing"
write_env "UPSTREAM_BRANCH" "master"
write_env "GIT_TOKEN" ""
write_env "SUPPORT_CHANNEL" "https://t.me/BillaSpace"
write_env "SUPPORT_CHAT" "https://t.me/BillaCore"
write_env "AUTO_LEAVING_ASSISTANT" "False"
write_env "SPOTIFY_CLIENT_ID" "1c21247d714244ddbb09925dac565aed"
write_env "SPOTIFY_CLIENT_SECRET" "709e1a2969664491b58200860623ef19"
write_env "PLAYLIST_FETCH_LIMIT" "350"
write_env "TG_AUDIO_FILESIZE_LIMIT" "104857600"
write_env "TG_VIDEO_FILESIZE_LIMIT" "1073741824"
write_env "STRING_SESSION" ""
write_env "STRING_SESSION2" ""
write_env "STRING_SESSION3" ""
write_env "STRING_SESSION4" ""
write_env "STRING_SESSION5" ""

echo "Created $ENV_FILE successfully!"
echo "Please review and fill in any empty values (like BOT_TOKEN, MONGO_DB_URI, etc.) as needed."
